language: rust
services:
  - docker

jobs:
  include:
    - stage: fmt
      script:
        - rustup component add rustfmt
        - cargo fmt -- --check
    - stage: lint
      script:
        - rustup component add clippy
        - cargo clippy --all-targets --all-features -- -D warnings
    - stage: test
      rust: stable
      script:
        - cargo build
        - cargo build --features=async
        - cargo test
        - cargo test --features=async
    - stage: test
      rust: nightly
      script:
        - cargo build
        - cargo build --features=async
        - cargo test
        - cargo test --features=async
    - stage: test
      before_install:
        - docker pull jbaublitz/ubuntu-musl
        - docker build -t rust-musl-ci test/rust-musl-ci
      script:
        - docker run -v $PWD:/neli -ti rust-musl-ci /bin/bash -c "cd /neli &&
          /usr/bin/git checkout $TRAVIS_COMMIT &&
          /root/.cargo/bin/rustup default stable-x86_64-unknown-linux-musl &&
          /root/.cargo/bin/cargo build &&
          /root/.cargo/bin/cargo build --features=async &&
          /root/.cargo/bin/cargo test &&
          /root/.cargo/bin/cargo test --features=async"
    - stage: test
      before_install:
        - docker pull jbaublitz/ubuntu-musl
        - docker build -t rust-musl-ci test/rust-musl-ci
      script:
        - docker run -v $PWD:/neli -ti rust-musl-ci /bin/bash -c "cd /neli &&
          /usr/bin/git checkout $TRAVIS_COMMIT &&
          /root/.cargo/bin/rustup default nightly-x86_64-unknown-linux-musl &&
          /root/.cargo/bin/cargo build &&
          /root/.cargo/bin/cargo build --features=async &&
          /root/.cargo/bin/cargo test &&
          /root/.cargo/bin/cargo test --features=async"
